### ISSUE TITLE
Loading data from OMERO

### ISSUE THREAD

**Issue by jstitlow** [DanuserLab/u-track#1]
Hi guys, 
Awesome software and very cool that you implemented OMERO! 
I can login to OMERO (5.4.10) through u-track but not able to load data. 
The error message is as follows:

`Error using horzcat
Dimensions of matrices being concatenated are not consistent.

Error in omeroDataSelectionGUI>omeroDataSelectionGUI_OpeningFcn (line 100)
groupIds = [groupIds1 groupIds2];

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});

Error in omeroDataSelectionGUI (line 59)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in movieSelectorGUI>menu_omero_load_Callback (line 625)
userData.omeroDataFig = omeroDataSelectionGUI('mainFig',handles.figure1);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in movieSelectorGUI (line 61)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)movieSelectorGUI('menu_omero_load_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.`

Does this look familiar?
Or would it be better to post this on OMERO message boards?

System specs: 
4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
MATLAB v. R2017b

Thanks!
Josh

**Comment by DanuserLab** [comment]
Since this issue dates back to 2019, we’ll go ahead and close this issue for now.
