### ISSUE TITLE
Docker launch incomplete

### ISSUE THREAD

**Issue by MugdhaSathe** [DanuserLab/u-track#11]
Hi,
I am trying to use u-track on macOS. I installed using the instructions however once u-track through docker the GUI is not showing up.  I used the following line from the instructions. 
docker run -ti --rm -e DISPLAY=${ipAddress}:0.0 jennyzouutsw/utrack2018b:1.0.0 bash /execute/utrack/run_utrack.sh /opt/mcr/v95 
Minor notes:
Some of the terminal based commands needs updating
1. To install xQuartz 
brew install xQuartz --cask
2. to add the IP 
 had to use : ssh -Y IP  #address

<img width="1171" alt="Screen Shot 2022-11-03 at 3 24 04 PM" src="https://user-images.githubusercontent.com/65699000/199845870-b9f50e58-e503-4b9e-a8b1-dc340f544b4d.png">

**Comment by DanuserLab** [comment]
Thank you for your message. We currently do not have access to a Mac to reproduce the issue you're experiencing with u-track and Docker. For the best experience, we recommend trying u-track on Linux or Windows.

If you continue to face issues, please feel free to reach out again.
