### ISSUE TITLE
Microtubule Dynamics: Forward and Backward Gaps

### ISSUE THREAD

**Issue by frankfazekas** [DanuserLab/u-track#12]
Hi u-track authors/editors,

I've been using u-track to detect and track MT tip comets, as described in the Danuser Lab's paper [here](https://pubmed.ncbi.nlm.nih.gov/21821130/). I'm particularly interested in using your software to characterize microtubule instability, namely catastrophe and rescue events.

No forward or backward events have been identified, however, in the "Microtubule dynamics classification" step, regardless of the value of the maximum gaps to close parameter. Is this an issue you've experienced before? All the data I'm working with are 2D. My working theory is that the problem may lie in plusTipCostMatCloseGaps.m. In line 180, for example, since all the entries of vz are NaN, the entries in velInst are also all NaN. There are some similar examples of z-components being NaN potentially throwing things off later on in the same function. Thanks for looking into this issue!

**Comment by DanuserLab** [comment]
Sorry for the delayed response. If you still need our assistance, please feel free to email us your detection results overlaid on your raw movie. Additionally, reviewing the documentation provided in the package may also be helpful. We will close this issue for now, but don’t hesitate to reach out if further support is needed.
