### ISSUE TITLE
What are the criteria for setting the search radius lower and upper bound? 

### ISSUE THREAD

**Issue by AnjalyPrasannajith** [DanuserLab/u-track#14]
Hi UTrack community,
I am trying to track Eb1 comets with UTrack. My movies are 31 frames taken at 2sec intervals in 2D. my average comet length is ~10pixels. 1 pixel=108.33 nm. How do I calculate what numbers to use for my search radius lower and upper bound? 

Any guidance will will greatly appreciated. Thank you for looking into this matter.

**Comment by DanuserLab** [comment]
Thanks for your message. If you still need our assistance, we’ll need more details about your project and dataset. Additionally, reviewing the documentation provided in the package may be helpful. We’ll close this issue for now, but please feel free to reach out if further support is needed.
