### ISSUE TITLE
Is PMMS available?

### ISSUE THREAD

**Issue by anntzer** [DanuserLab/u-track#4]
Dear authors,
Your manuscript "Piecewise-stationary motion modeling and iterative smoothing to track heterogeneous particle motions in dense environments" (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5796444) states that "Our new motion model and estimator will part of the next release of the u-track platform at http://www.utsouthwestern.edu/labs/danuser/software/."
Is PMMS now available?  I cannot find it in this repo, though I may have missed something.
Thanks in advance.

**Comment by DanuserLab** [comment]
Thank you for your interest in our work and for reaching out. I recommend contacting [Dr. Philippe Roudot](https://centuri-livingsystems.org/p-roudot/) directly for this question. You can also check out the u-track3D package, which might contain relevant features: https://github.com/DanuserLab/u-track3D.
