### ISSUE TITLE
MetaData

### ISSUE THREAD

**Issue by younesba** [DanuserLab/u-track#6]
Hi,  when I try to save the files after, steps of movie creation from. series of tiff files as mentioned in the pdf.  I get the message below "Invalid or. detected object. please check your movie data? Movie data is not saved"

in the Matlab command windows the message is : matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)movieDataGUI('pushbutton_view_metadata_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback 

Please help to solve this problem because. 

Thanks

**Comment by DanuserLab** [comment]
Thank you for reaching out. To resolve the issue you're encountering, please follow these steps:

Download the latest version of u-track from our repository.
In MATLAB, reset the path to its default by using the following command:
`restoredefaultpath`
After resetting, add the u-track folder and all its subfolders to the MATLAB path.

Once you've done this, try running the steps again and let us know if the issue persists.
