### ISSUE TITLE
cannot load the library of mex

### ISSUE THREAD

**Issue by rayliulhr** [DanuserLab/u-track#7]
I am using Mac. The U-track failed to load the library of mex. Can anyone help me with this issue?
identifier: 'MATLAB:mex:ErrInvalidMEXFile'
message: 'Invalid MEX-file '
Library not loaded: @loader_path/libmex.dylib

**Comment by DanuserLab** [comment]
Thank you for reaching out. We recommend running u-track on Linux or Windows for the best experience. While u-track should work on macOS with Intel processors, it will not currently work on macOS with Apple Silicon. Unfortunately, MEX files built on macOS with Intel are not supported on the Apple Silicon platform using Rosetta 2. When running u-track on macOS with Intel processors, please ensure that dependency libraries are correctly installed on your Mac. 

At the moment, we do not have macOS with Apple Silicon available to recompile all the MEX files. However, we are working hard on solving this issue. Thank you for your patience.
