### ISSUE TITLE
QuickTime for Java is not supported with a 64-bit JVM

### ISSUE THREAD

**Issue by vanqilei** [DanuserLab/u-track#9]
Hi guys,i ran into this problem when loading .mov.I just don't know how to figure it out.
The program is running on win10,matlab2019b and it tells:
Java exception occurred:
    loci.formats.MissingLibraryException: QuickTime for Java is not supported with a 64-bit JVM. Please invoke the 32-bit
    JVM (-d32) to utilize QTJava functionality.
Can anyone help me with it?

**Comment by DanuserLab** [comment]
Thank you for reaching out. The error you're encountering indicates that QuickTime for Java is not supported with a 64-bit JVM. To resolve this issue, you'll need to run MATLAB with a 32-bit Java Virtual Machine (JVM). You may also try using a newer version of Matlab. Thank you.
